"""
Project Globals
"""
from enum import Enum
from pathlib import Path

COLLECTION_NAME = "macro_regimes"

"""
Federal Reserve Data

    MANEMP (manufacturing employment) — late 1930s
    CPIAUCSL, UNRATE, real GDP — mid-to-late 1940s
    FEDFUNDS — 1954
    PCEPI — 1959
    T10Y2Y (10y–2y spread) — mid-1970s
    USALOLITOAASTSAM (OECD composite leading indicator, US) — monthly

"""
HISTORY_SEED_START="1999-01-01"  # driven by when we have data for most SPDR ETFs

SUPPORTED_SERIES = {
    'fed_funds_rate':    'FEDFUNDS',    # [MONTHLY]
    'cpi':               'CPIAUCSL',    # [MONTHLY]
    'pce_inflation':     'PCEPI',       # [MONTHLY]
    'unemployment':      'UNRATE',      # [MONTHLY]
    'yield_spread_10_2': 'T10Y2Y',      # 10yr minus 2yr Treasury ## [DAILY]
    'gdp_growth':        'A191RL1Q225SBEA',  # real GDP, quarterly ## [QUARTERLY]
    'ism_pmi':           'MANEMP',      # manufacturing employment as PMI proxy ## [MONTHLY]
    'leading_index':     'USALOLITOAASTSAM',  # OECD composite leading indicator (US, amplitude-adjusted) ## [MONTHLY]
}
## For the historical series, we'll add cpi_you calculated
CPI_INFLATION_SERIES = 'cpi_inflation'

UNEMPLOYMENT_CHANGE_SERIES = "unemployment_chg_3m"
LEADING_INDEX_CHANGE_SERIES = "leading_index_slope"

# Human-readable labels + FRED provenance for the snapshot indicators. cpi_inflation
# is the lone DERIVED series (YoY of CPIAUCSL), so it doesn't map 1:1 through
# SUPPORTED_SERIES the way the direct pulls do -- its tag is spelled out.
_INDICATOR_LABELS: dict[str, str] = {
    "fed_funds_rate":    "Federal Funds Rate",
    "cpi_inflation":     "CPI Inflation (YoY)",
    "pce_inflation":     "PCE Inflation",
    "unemployment":      "Unemployment Rate",
    "yield_spread_10_2": "10yr-2yr Treasury Spread",
    "gdp_growth":        "Real GDP Growth",
    "ism_pmi":           "Manufacturing Employment (PMI proxy)",
    "leading_index":     "Leading Economic Index",
}

# Guardrail #5 (spec Section 9): the fixed disclaimer every brief must carry, verbatim.
DISCLAIMER: str = (
    "This output is generated by an AI research agent for educational and "
    "analytical purposes only. It does not constitute investment advice."
)

"""
YFinance Data
The nine original Select Sector SPDRs start December 1998, XLRE in 2015, XLC in 2018.

"""
SECTOR_ETFS = {
    'XLK':  'Technology',
    'XLF':  'Financials',
    'XLE':  'Energy',
    'XLV':  'Health Care',
    'XLI':  'Industrials',
    'XLU':  'Utilities',
    'XLP':  'Consumer Staples',
    'XLY':  'Consumer Discretionary',
    'XLB':  'Materials',
    'XLRE': 'Real Estate',
    'XLC':  'Communication Services',
}

# The 11 GICS sector ETFs tracked by the agent (see spec Section 6.2).
SECTOR_ETFS_LIST: tuple[str, ...] = (
    "XLK", "XLF", "XLE", "XLV", "XLI",
    "XLU", "XLP", "XLY", "XLB", "XLRE", "XLC",
)

# --------------------------------------------------------------------------- #
# Named sector sub-universes (spec Section 3.1 / 10.1 -- query "focus").
#
# A query can ask to rank a SUBSET of the 11 sectors ("which DEFENSIVE sectors ...").
# The decomposer resolves a named group (or an explicit ticker list) to a focus universe
# that compute_sector_score ranks over; the FULL universe is still fetched and fed to the
# macro ToT, so narrowing the focus never changes the regime call -- only which sectors
# appear in the ranking. Groups intentionally OVERLAP and are not a partition;
# "rate_sensitive" is directionally mixed (XLF gains from higher rates while XLU/XLRE
# suffer). Domain assumptions -- tune freely.
# --------------------------------------------------------------------------- #
SECTOR_GROUPS: dict[str, tuple[str, ...]] = {
    "defensive":      ("XLU", "XLP", "XLV"),
    "cyclical":       ("XLY", "XLI", "XLB", "XLF", "XLE"),
    "rate_sensitive": ("XLU", "XLRE", "XLF"),
    "growth":         ("XLK", "XLC", "XLY"),
}

# The indicators that form the vector, in a FIXED order. This exact tuple must
# be used by both seed and query. 
###  DO NOT CHANGE ORDER -- places in the code depend in this ###
INDICATOR_KEYS: tuple[str, ...] = (
    "fed_funds_rate",
    "cpi_inflation",
    "pce_inflation",
    "unemployment",
    "yield_spread_10_2",
    "gdp_growth",
    "ism_pmi",
    "leading_index",
)
"""
STEEP CURVE
Early-cycle recoveries run steep (the 10y–2y hit roughly +2.5 to +2.8 in 1992, 2003–04, and 2010–11),
  so anything north of ~1 point is unambiguously "the Fed has cut, long rates well above short." 
  A stricter early-cycle gate could push to 1.5.
"""
STEEP_CURVE = 1.0
"""
FLAT CURVE
Curve has compressed toward zero, i.e. flattening into inversion, the classic late-cycle/pre-recession tell.
  If the late-cycle branch should only fire on an actual inversion, set it to 0.0.
  (the curve went negative — 2000, 2006-07, 2019, 2022-23 all preceded recessions this way)
"""
FLAT_CURVE = 0.25
"""
HOT INFLATION
Economically this is "inflation running meaningfully above the Fed's 2% target," 
  so ~3% year-over-year is the defensible line (2.5-3.5% is the reasonable range to tune within).
"""
HOT_INFLATION = 3.0

"""
LEADING INDEX NEUTRAL
The OECD composite leading indicator (USALOLITOAASTSAM) is an INDEX centered on 100:
  >100 signals above-trend growth ahead, <100 signals weakness. This replaced the
  discontinued USSLIND (a growth rate centered on 0), so _label_regime's early-cycle
  test compares the leading index against THIS neutral level rather than against 0.
"""
LEADING_INDEX_NEUTRAL = 100.0

# --------------------------------------------------------------------------- #
# Control parameters for ToT reasoning.
# Tune these against a backtest to balance responsiveness vs noise sensitivity.
#
# Defining them here, for easy tuning...
# --------------------------------------------------------------------------- #
MAX_BRANCHES = int(3)  # how many candidates to fan out into
ANALOGS_PER_BRANCH = int(8)  # how many historical analogs to retrieve when evaluating each branch.
# More analogs gives a more robust support score but costs more tokens. 5-10 is a reasonable range.
TIE_MARGIN = float(0.05)  # margin for flagging low confidence results
# TIE_MARGIN: if the top two branches have support scores within this margin, we flag the result as low confidence.
# Tune this based on how noisy the support scores are and how much overlap occurs between branches.

# --------------------------------------------------------------------------- #
# Control parameters for agents.
# 
# Defining them here, for easy tuning...
# --------------------------------------------------------------------------- #
MAX_HYPOTHESES = int(3)
MAX_HISTORICAL_ANALOGS = int(10)
FED_NARRATIVE_TOP_K = int(5)

# --------------------------------------------------------------------------- #
# Analog forward-return horizons (spec Section 3.3 / 3.4).
#
# The analog store seeds each historical month's forward sector returns at SEVERAL
# horizons, so a query's requested horizon can be honored in scoring (compute_sector_score
# selects the matching slice). ANALOG_DEFAULT_HORIZON_MONTHS is the window used when a
# query states no horizon -- and the slice older single-horizon stores carry -- so it MUST
# be a member of ANALOG_HORIZONS_MONTHS. A requested horizon outside this set falls back to
# the default, with the report flagging the gap. Re-seed (python -m
# sector_rotation_agent.historical_analogs) after changing these.
# --------------------------------------------------------------------------- #
ANALOG_HORIZONS_MONTHS: tuple[int, ...] = (3, 6, 12)
ANALOG_DEFAULT_HORIZON_MONTHS: int = 6

# --------------------------------------------------------------------------- #
# Audit layer -- data-freshness ceilings (spec Section 9, guardrail #2).
#
# The freshness check flags an indicator whose most recent observation is older
# than its ceiling (in days). FRED dates each observation at the START of its
# period and releases lag the period, so a genuinely-current point's "age" is
# roughly (period length) + (release lag) + slack. The default below fits MONTHLY
# series read mid-month; only series with a longer cadence need an override here,
# or they trip the freshness check on every run despite holding the latest data.
# Tunable domain assumptions, like the scorer weights.
# --------------------------------------------------------------------------- #
DEFAULT_MAX_AGE_DAYS: int = 45   # spec guardrail #2; fallback for any unmapped series
FRESHNESS_MAX_AGE_DAYS: dict[str, int] = {
    # gdp_growth (A191RL1Q225SBEA) is QUARTERLY, dated at the quarter start, with a
    # multi-week reporting lag -- so the latest genuinely-current print can be ~5
    # months old before the next quarter posts. ~200 days clears a normal quarter +
    # lag while still catching a truly missed release; 45 would flag it every run.
    "gdp_growth": 200,
    # leading_index (OECD CLI USALOLITOAASTSAM) is MONTHLY, but OECD publishes with a
    # ~6-week lag, so the latest current print is ~1.5 months old plus the monthly gap
    # before the next release. ~75 days clears that without nuisance-flagging a current
    # series; the 45-day default would trip nearly every run.
    "leading_index": 75,
}

# --------------------------------------------------------------------------- #
# Enum - types of the business-cycle we'll have the model classify into.
# --------------------------------------------------------------------------- #
class Regime(str, Enum):
    """Canonical business-cycle regimes the agent can classify into."""
    EARLY_CYCLE = "early_cycle"        # recovery / early expansion
    MID_CYCLE = "mid_cycle"            # steady expansion
    LATE_CYCLE = "late_cycle"          # peak / slowing expansion
    CONTRACTION = "contraction"        # recession / early downturn

# --------------------------------------------------------------------------- #
# Chroma DB config — seed and query MUST share all of this
# --------------------------------------------------------------------------- #
_PROJECT_ROOT = Path(__file__).resolve().parents[2]
STORE_PATH = _PROJECT_ROOT / "data" / "chroma"           # persistent Chroma dir
NORM_STATS_PATH = _PROJECT_ROOT / "data" / "norm_stats.json"
COLLECTION_NAME = "macro_regimes"

# --------------------------------------------------------------------------- #
# Location of the MCP Servers
# --------------------------------------------------------------------------- #
MCP_SERVERS_PATH = Path(__file__).parent / "mcp_servers"
MCP_CLIENT_FRED = "fred_server.py"
MCP_CLIENT_YFIN = "yfin_server.py"


# --------------------------------------------------------------------------- #
# Enum - valid configuration of model types.
# --------------------------------------------------------------------------- #
class ModelLocations(str, Enum):
    """Canonical business-cycle regimes the agent can classify into."""
    LOCAL_ONLY = "local_only"         # only use local models
    MIXED = "mixed"                 # mix of cloud and local models
    CLOUD_ONLY = "cloud_only"          # peak / slowing expansion